---
name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build
    container: fedora:39
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          cat > /etc/yum.repos.d/oneAPI.repo <<EOF
          [oneAPI]
          name=Intel® oneAPI repository
          baseurl=https://yum.repos.intel.com/oneapi
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          EOF

          dnf -y update && \
            dnf -y install intel-oneapi-mkl \
              intel-oneapi-mkl-devel \
              intel-oneapi-compiler-shared-runtime-2024.0 \
              intel-oneapi-openmp-common-2024.0 \
              intel-oneapi-openmp-2024.0 \
              libomp \
              libgomp \
              gcc \
              g++ \
              clang \
              clang-devel \
              clang-libs \
              pkgconf-pkg-config
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install Cargo Hack
        run: |
          cargo install cargo-hack
      - name: Build
        run: |
          cargo hack build --each-feature --exclude-no-default-features \
            --exclude-all-features --exclude-features no-link,sdl
      - name: Test
        run: |
          cargo hack test --each-feature --exclude-no-default-features \
            --exclude-all-features --exclude-features no-link,sdl
